# -*- coding: utf-8 -*-
"""Pandas Ödev.7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZfVbXkY-cfir1JAJDk8JsTrtHBS45jr
"""

sozluk = {"Kategori": ["Giyim","Giyim", "Ayakkabı","Aksesuar","Ayakkabı","Giyim","Aksesuar","Aksesuar","Ayakkabı","Giyim"],
         "Ürün" : ["Kazak","T-shirt","Sandalet","Küpe","Spor Ayakkabı","Pantolon","Kolye","Yüzük","Çizme","Ceket"],
         "Fiyat" : [300,180,450,50,700,400,150,80,850,900]}

"""##### 1. Yukarıdaki sözlüğü bir DataFrame haline getirin."""

pip install pandas

import pandas as pd

sozluk={"Kategori":["Giyim","Giyim","Ayakkabı","Aksesuar","Ayakkabı","Giyim","Aksesuar","Aksesuar","Ayakkabı","Giyim"],
        "Ürün":["Kazak","T-shirt","Sandalet","Küpe","Spor Ayakkabı","Pantolon","Kolye","Yüzük","Çizme","Ceket"],
        "Fiyat":[300,180,450,50,700,400,150,80,850,900]}

sozluk=pd.DataFrame({"Kategori":["Giyim","Giyim","Ayakkabı","Aksesuar","Ayakkabı","Giyim","Aksesuar","Aksesuar","Ayakkabı","Giyim"],
                     "Ürün":["Kazak","T-shirt","Sandalet","Küpe","Spor Ayakkabı","Pantolon","Kolye","Yüzük","Çizme","Ceket"],
                     "Fiyat":[300,180,450,50,700,400,150,80,850,900]})
sozluk

"""##### 2. Aşağıdaki işlemleri dataframe üzerinde uygulayalım.
- 2.indexde bulunan kategoriyi bulalım (Sadece kategori bilgisi)
- 2.indexde bulunan ürünü bulalım (Sadece ürün bilgisi)
- 4.indexden 9.indexe kadar olan verileri bulalım (Kategori,ürün,fiyat bilgisi beraber)
- 1.indexden 6.indexe kadar olan ürünleri bulalım (Sadece ürün bilgisi)

"""

sozluk["Kategori"][1]

sozluk["Ürün"][1]

sozluk[["Kategori","Ürün","Fiyat"]][3:9]

sozluk["Ürün"][1:6]

"""##### 3. Aşağıdaki işlemleri dataframe üzerinde uygulayalım.
- Giyim kategorisinde bulunan ürünleri gösterin
- Ayakkabı kategorisinde bulunan ürünleri gösterin
- Aksesuar kategorisinde bulunan ürünleri gösterin
"""

sozluk=pd.DataFrame({"Kategori":["Giyim","Giyim","Giyim","Giyim"],"Ürün":["Kazak","T-shirt","Pantolon","Ceket"]})
sozluk

sozluk=pd.DataFrame({"Kategori":["Ayakkabı","Ayakkabı","Ayakkabı"],"Ürün":["Sandalet","Spor Ayakkabı","Çizme"]})
sozluk

sozluk=pd.DataFrame({"Kategori":["Aksesuar","Aksesuar","Aksesuar"],"Ürün":["Küpe","Kolye","Yüzük"]})
sozluk

"""##### 4 Aşağıdaki işlemleri dataframe üzerinde uygulayalım.
- Giyim kategorisinde fiyatı 300'den fazla olan ürünleri gösterin
- Ayakkabı kategorisinde fiyatı 600'den az olan ürünleri gösterin
- Aksesuar kategorisinde fiyatı 100'den fazla olan aksesuarı gösterin
"""

sozluk=[{"Fiyat":[300,180,450,50,700,400,150,80,850,900]}]
fiyat_listesi=sozluk[0]["Fiyat"]
filtreli_fiyat=[fiyat for fiyat in fiyat_listesi if fiyat >300]
filtreli_fiyat

import pandas as pd

veri1= pd.DataFrame({"Kategori":["Giyim","Giyim","Giyim","Giyim"],"Ürün":["Kazak","T-shirt","Pantolon","Ceket"],"Fiyat":[300,180,400,900]})
df=pd.DataFrame(veri1)
giyim_filtre=(df["Fiyat"]>300)
giyim_sonuç= df[giyim_filtre]
print(giyim_sonuç)

import pandas as pd
veri2=pd.DataFrame({"Kategori":["Ayakkabı","Ayakkabı","Ayakkabı"],"Ürün":["Sandalet","Spor Ayakkabı","Çizme"],"Fiyat":[450,700,850]})
df=pd.DataFrame(veri2)
ayakkabı_filtre=(df["Fiyat"]<600)
ayakkabı_sonuç=df[ayakkabı_filtre]
print(ayakkabı_sonuç)

veri3=pd.DataFrame({"Kategori":["Aksesuar","Aksesuar","Aksesuar"],"Ürün":["Küpe","Kolye","Yüzük"],"Fiyat":[50,150,80]})
df=pd.DataFrame(veri3)
aksesuar_filtre=(df["Fiyat"]>100)
aksesuar_sonuç=df[aksesuar_filtre]
print(aksesuar_sonuç)