# -*- coding: utf-8 -*-
"""Students_Performance_Ödev8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgixYWq8JZD_kAyG7sFovo57yduAmvlY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.read_csv("StudentsPerformance.csv")

veri= pd.read_csv("StudentsPerformance.csv")
df=pd.DataFrame(veri)
df.head()

df.tail()

df.info()

df.value_counts()

df.axes

#2
#kadın-erkek sayısına bakalım

df["gender"].value_counts()

group_gender_size=df["gender"].value_counts().reset_index()
group_gender_size

#3
#kadın-erkek sayısına histogram grafiği ile bakalım

import matplotlib.pyplot as plt
import seaborn as sns

group_gender_size=df["gender"].value_counts().reset_index()
plt.figure(figsize=(6,5))
plt.title("StudentPerformance")
plt.bar(x="gender",height="count",data=group_gender_size)
plt.xticks(rotation=90);

#4
#race/ethnicity sütununda kaç farklı grup olduğuna bakalım

race=df["race/ethnicity"].value_counts()
race

new_table2=pd.DataFrame(df["gender"].value_counts() & df["race/ethnicity"])
new_table2

race = df["race/ethnicity"].value_counts()
race

#5
#yukarıda bulduğumuzu görselleştirelim

new_table2=df["race/ethnicity"].value_counts().reset_index()
plt.figure(figsize=(12,6))
plt.title("StudentPerformance")
plt.bar(x="race/ethnicity",height="count",data=new_table2)
plt.xticks(rotation=90);

#6
#parental level of education sütunundaki eşsiz değerleri bulalım

df["parental level of education"].value_counts()

new_table3=df["parental level of education"].value_counts().reset_index()
plt.figure(figsize=(12,6))
plt.title("StudentPerformance")
plt.bar(x="parental level of education",height="count",data=new_table3)
plt.xticks(rotation=90);

#7
#lunch sütununda eşsiz değerlere ulaşalım

df["lunch"].unique()

#8
#lunch türlerinde kaçar kişi olduğunu bulalım

df["lunch"].value_counts()

new_table4=df["lunch"].value_counts().reset_index()
plt.figure(figsize=(12,6))
plt.title("StudentPerformance")
plt.bar(x="lunch",height="count",data=new_table4)
plt.xticks(rotation=90);

df["test preparation course"].value_counts()

new_table5=df["test preparation course"].value_counts().reset_index()
plt.figure(figsize=(12,6))
plt.title("StudentPerformance")
plt.bar(x="test preparation course",height="count",data=new_table5)
plt.xticks(rotation=90);

#9
#gender sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

pd.read_csv("StudentsPerformance.csv")

gender_value=df["gender"].value_counts().mean()
gender_value

#10
#race/ethnicity sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

df["race/ethnicity"].value_counts().mean()

#11
#parental level of education sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

df["parental level of education"].value_counts().mean()

#12
#lunch sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

df["lunch"].value_counts().mean()

#13
#test preparation course sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

df["test preparation course"].value_counts().mean()

